# Generated by Django 4.2.7 on 2024-04-14 09:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categories",
            options={"verbose_name": "категорию", "verbose_name_plural": "категории"},
        ),
        migrations.AlterModelTable(
            name="categories",
            table="category",
        ),
    ]
